### ISSUE TITLE
Draw player model in dem_forcehltv freecam

### ISSUE THREAD

**Issue by SmileyAG** [YaLTeR/bxt-rs#10]
maybe it will be helpful somehow, https://github.com/advancedfx/advancedfx/blob/main/AfxHookGoldSrc/HltvFix.cpp

**Comment by YaLTeR** [comment]
What does it do?

**Comment by SmileyAG** [comment]
Drawing player model in freecam.

**Comment by SmileyAG** [comment]
Closed that issue, since I implement that to BXT: https://github.com/YaLTeR/BunnymodXT/pull/238
