### ISSUE TITLE
How to load CS 1.6 demo?

### ISSUE THREAD

**Issue by eightbo** [YaLTeR/bxt-rs#107]
I can successfully launch bxt-rs with hl.exe but I can't load any demos from my cstrike folder

Stuff I tried but didn't work:
- Injecting to Counter-Strike.exe with PowerShell instead of hl.exe (game loads but bxt_ console commands not present)
- Selecting "Change Game" then selecting "Counter Strike" in Half Life Menu but it just relaunches to HL1
- Moving demos to root folder (where hl.exe is)

Demos in cstrike folder are simply not detected (they work normally with HLAE)

```
] viewdemo kzlv_vaz_ujo_e_eightbO_0127.83.dem
Playing demo from kzlv_vaz_ujo_e_eightbO_0127.83.dem.
Coudn't open demo file kzlv_vaz_ujo_e_eightbo_0127.83.dem.
Viewdemo: couldn't load demo kzlv_vaz_ujo_e_eightbO_0127.83.
```

**Comment by khanghugo** [comment]
Did you add `-game cstrike` argument to the command?

**Comment by eightbo** [comment]
> Did you add `-game cstrike` argument to the command?

This was it — thank you!  It wasn't mentioned in the v1.0 tutorial.  

P.S. I'll mark this as 'Completed' but if any admin wants to move/delete as appropriate go ahead.
