### ISSUE TITLE
New to studio Tas

### ISSUE THREAD

**Issue by YourLocalAssistantGuy** [YaLTeR/bxt-rs#111]
Hey there! I'm just new to tasing and yes its me, I just want to know that how do I make the character just stops like it dosent move.

**Comment by khanghugo** [comment]
GitHub issue tracker is not the appropriate place for you to ask this question. Go to #goldrc-tas channel in Sourceruns discord if you want to ask specific questions related to using tas editor. https://discord.gg/sourceruns

**Comment by YourLocalAssistantGuy** [comment]
Alr thx
