### ISSUE TITLE
WON engine support (video recording & hud scaling)

### ISSUE THREAD

**Issue by SmileyAG** [YaLTeR/bxt-rs#30]
Related: #28

**Comment by YaLTeR** [comment]
I need to review and add a thing similar to LoadAndDecryptHwDLL from BXT.

**Comment by YaLTeR** [comment]
Otherwise non-SDL OpenGL already works fine.

**Comment by SmileyAG** [comment]
Fixed in https://github.com/YaLTeR/bxt-rs/commit/7e51ae60651e5f093497cf8fb67b202280f185c9 & https://github.com/YaLTeR/bxt-rs/commit/265b54107072ba02a3f75a1368cfb60bc3e6734a
