### ISSUE TITLE
Shortest demo cancels a multiple playback (bxt_play_run)

### ISSUE THREAD

**Issue by SmileyAG** [YaLTeR/bxt-rs#34]
Is it possible to skip 0.01s and lower time demos from playback somehow?

**Comment by YaLTeR** [comment]
Can you attach some example demo that exits to the main menu?

**Comment by SmileyAG** [comment]
> Can you attach some example demo that exits to the main menu?

[test.zip](https://github.com/YaLTeR/bxt-rs/files/7772121/test.zip)

**Comment by SmileyAG** [comment]
Closes as it fixed in https://github.com/YaLTeR/bxt-rs/commit/0ecf48d5e65079b767155281a2ff6aa046f5cc07
