### ISSUE TITLE
bxt_cap_start video name requires .mp4 or .wav suffix 

### ISSUE THREAD

**Issue by khanghugo** [YaLTeR/bxt-rs#57]
I am wondering if we can make this not intentional. Since the video is sure to be mp4 or wav format, maybe it is possible to just add that implicitly? In the case of just record the audio, maybe we can have a cvar for that?

**Comment by khanghugo** [comment]
Instead of having the file name dictate whether to record audio and video, I think having a cvar doing that seems easier. This could play well with #56 problem of `bxt_cap_start` specified file name.

**Comment by YaLTeR** [comment]
It is intentional because if you put a wrong extension it can result in weird ffmpeg errors or broken output. I don't think it's a good idea to let people use extensions which aren't explicitly supported.

**Comment by khanghugo** [comment]
What do you think of having no extension specified in `bxt_cap_start` argument? Because right now the only use where there is a need for file extension is recording audio only. And the extension of video is just .mp4 so that can be added when filename is given.

**Comment by YaLTeR** [comment]
The current system where you set .mp4 for video and .wav for audio seemed pretty natural to me. Idk though, maybe I'm mistaken? Windows hides extensions by default, is that something people capturing videos use?

**Comment by khanghugo** [comment]
Hmmm, it just has something related to #56 where one command of `bxt_cap_start` can start recording and split the recording for each demo accordingly. If there were input for `bxt_cap_start`, say something like `bxt_play_folder foldername; bxt_cap_start output.mp4` to record demos with each of their own video, how the "output.mp4" is interpreted right now could challenge the idea. I propose to just have the specified file name as just "output". If there were a flag (cvar) to record demos individually, that file name could be either the folder they are in or the prefix for the output (or both). And also for that, there will be no reminder of adding ".mp4" or ".wav" when we do the normal `bxt_cap_start filename`. The reason I am seeing why there is a need to add file extension to `bxt_cap_start` at the moment is to record audio, which I think could be controlled with a cvar instead of file extension like this.

```
] bxt_cap_start output
Error: the filename must end with ".mp4" or ".wav".
```

Maybe I am not good with words to describe it right now but I could scrap together a pr for mentioned issue then maybe it can show.

**Comment by YaLTeR** [comment]
> bxt_play_folder foldername; bxt_cap_start output.mp4 to record demos with each of their own video,

I am not yet 100% convinced this is a good way to invoke it. Still need to think more about it.

**Comment by khanghugo** [comment]
For now I just think it is the better way to play well with already existing `bxt_cap_start` without adding another capture command just specifically for another kind of capture. But anyway, I can get a working implementation for split recording  and then maybe there will be some progresses.

**Comment by YaLTeR** [comment]
I think with the other suggestion this can be closed.
