### ISSUE TITLE
Error creating process: Access is denied.

### ISSUE THREAD

**Issue by classicstrike** [YaLTeR/bxt-rs#89]
Injector.exe "path\to\hl.exe\dir"
`Error creating process: Access is denied.`

- Running cmd as admin on Windows 11
- Tried putting injector in same dir as hl.exe
- Changed the security settings of hl.exe dir to have full permissions
- Tried running with high integrity level

**Comment by khanghugo** [comment]
The path you have to the executable is incorrect. You need to give the correct path.

Eg, I have the game in D:\games\hl1\hl.exe then that will be the path to executable

**Comment by khanghugo** [comment]
If you have the injector in the game folder along with bxt_rs.dll, then do

Injector.exe .\hl.exe

I don't recomment putting stuffs into the game folder because as far as I know no one knows how VAC works and it could scan your game folder.

**Comment by classicstrike** [comment]
You're right but now this

![Screenshot 2023-12-10 032845](https://github.com/YaLTeR/bxt-rs/assets/138153637/91cd4163-989a-4436-9712-df34622c4182)

**Comment by khanghugo** [comment]
You are running on latest half life version. bxt-rs for now does not work on latest half life on windows. You should revert it back to legacy version.

**Comment by YaLTeR** [comment]
Yeah, bxt-rs currently does not work on the anniversary update version. If you have any further questions please ask in https://discord.gg/sourceruns in #goldsrc-help.
